# Generated by Django 3.1 on 2021-04-15 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('reg', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('session', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseId', models.CharField(max_length=12)),
                ('courseName', models.CharField(max_length=60)),
                ('semester', models.IntegerField()),
                ('credit', models.DecimalField(decimal_places=2, max_digits=3)),
                ('isMajor', models.BooleanField()),
                ('isLab', models.BooleanField()),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('stuId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.student')),
            ],
        ),
    ]
