# Generated by Django 3.1 on 2021-04-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_auto_20210421_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cgpa',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='credits',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
