# Generated by Django 3.1 on 2021-04-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_auto_20210422_0621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('desc', models.TextField()),
            ],
        ),
    ]
